name: Docker Build & Measure (Alpine)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start build timer
        id: start-time
        run: echo "time=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Pull base image (alpine)
        run: docker pull python:3.12-alpine

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image from Dockerfile.alpine
        id: build
        run: |
          docker build -f Dockerfile.alpine -t spaceship-app:alpine .
          docker image inspect spaceship-app:alpine --format='{{.Size}}' > image_size.txt

      - name: End build timer
        id: end-time
        run: echo "time=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Calculate build duration and image size
        run: |
          START=${{ steps.start-time.outputs.time }}
          END=${{ steps.end-time.outputs.time }}
          DURATION=$((END - START))
          SIZE=$(cat image_size.txt)
          echo "Build time: $DURATION seconds"
          echo "Image size: $((SIZE / 1024 / 1024)) MB"

      - name: Done
        run: echo "Docker Alpine build complete"
